### PR TITLE
Set up initial directory structure

### PR DESCRIPTION
**Pull request by grahamearley**
Add directories with placeholder files explaining purpose of their directories.

### CODE REVIEW

**Comment by grahamearley** [comment]
Looks good, I say go for it.

**Review by brennan724 — APPROVED** [review]
I approve.  Prairie is go.

**Review by Donahuec — APPROVED** [review]

**Review by shoemakerc — APPROVED** [review]
My name is Chris Shoemaker and I approve this issue.

**Review by mjavaly — APPROVED** [review]
10/10 would prairie again

**Pull request merged**
