### PR TITLE
Fixed pivot point for swivel.

### LINKED ISSUE #136: Door Rotation Axis Picking
In our brief demo this morning, it seemed the `Swivel` interaction didn't always select the correct pivot point (wrong axis).

It should pick the correct axis for pivot based on whether its width (length along x axis) or depth (length along z axis) is greater.

### PR DESCRIPTION
**Pull request by mjavaly**
Because we use the local X, Y, Z to find the pivot point for the object, the values we obtain do not relate to the user. Therefore, the width of the door could theoretically be any one of them. I just found the second-largest one (the largest being the height) and assumed that the object being rotated kind of already LOOKS like a door. This resolves #136

### CODE REVIEW

**Review by cpimhoff — CHANGES_REQUESTED** [review]
Much better but still a bit weird on some doors.

example weird pivot

Here's the door as a still so you can see which axises are extended. The door does not have any rotation (prior to being swiveled for the first time).
screen shot 2017-02-10 at 11 55 16 pm

**Comment by cpimhoff** [comment]
@mjavaly, I've pushed the scene I used for testing - (which contains the door in question).

**Comment by mjavaly** [comment]
@cpimhoff I think I fixed everything - let me know if you can find any bugs

**Review by Donahuec — APPROVED** [review]
Looks good, and all of the doors in Charlie's test scene seem to work.

I'm mildly entertained by the swivelly ground doors.  

I'm guessing it wouldn't work for doors that don't face upwards? (such as trap doors, or angled cellar doors) I also think those are not actually important and we shouldn't worry about them...

**Pull request merged**
