### PR TITLE
Gun Mode

### PR DESCRIPTION
**Pull request by cpimhoff**
geez. Not sure how we didn't catch this sooner!
Prairie was completely without a gun mode!

## This PR introduces Gun Mode (finally)

Gun Mode
https://gfycat.com/JampackedPleasingBallpython

This PR resolves all open issues.

### CODE REVIEW

**Review by grahamearley — CHANGES_REQUESTED** [review]
So does this have other weapons included? I think users would like the option to use a rocket launcher. Please update with these changes.

**Comment by grahamearley** [comment]
Been thinking about this a lot, and I don't know if this update fits in with Prairie if we don't have rocket launchers

**Comment by cpimhoff** [comment]
I think rocket launchers and other "power weapons" (such as the magma blade) should be planned as Day One DLC.

**Review by mjavaly — APPROVED** [review]
I would like to start by saying OMG but while also acknowledging that this is a vital aspect of our infrastructure and I'm surprised no one has taken such initiative until now. good work Charlie.

**Review by shoemakerc — APPROVED** [review]
please merge

**Comment by cpimhoff** [comment]
While I'm a big fan of the innovative and action packed gameplay of _Gun Mode_, it is with heavy heart that I announce the cancellation of this PR.

After extensive user testing, it seems like historians **just aren't ready** for something this groundbreaking.

**Comment by grahamearley** [comment]
Truly a sad day in Prairie history

**Pull request closed without merging**
