### PR TITLE
Charlie's Code Style Changes

### PR DESCRIPTION
**Pull request by cpimhoff**
This PR includes basic style changes and minor documentation additions for all of Charlie's code currently on `master`.

### CODE REVIEW

**Review by grahamearley — APPROVED** [review]
👍

**Review by mjavaly — APPROVED** [review]
looks good! will follow these changes.

**Review by grahamearley — APPROVED** [review]
nice

**Review by Donahuec — APPROVED** [review]

**Review by brennan724 — COMMENTED** [review]
looks good!

**Pull request merged**
